find_library( BFD_LIBRARY	NAMES bfd	PATH ${CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES} )

if ( BFD_LIBRARY )
	set( BFD_FOUND TRUE )
	message( STATUS "Found libbfd: ${BFD_LIBRARY}")
endif ( BFD_LIBRARY )
